import Link from "next/link";
import "./globals.css";
import styles from "./page.module.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <nav className={styles.nav}>
          <div className={styles.row}>
            <p className={styles.heading}>supabase-js</p>
            <Link prefetch={false} href="/supabase/static">
              static
            </Link>
            <Link prefetch={false} href="/supabase/static-with-revalidate">
              static-with-revalidate
            </Link>
            <Link prefetch={false} href="/supabase/ssr">
              ssr
            </Link>
            <Link prefetch={false} href="/supabase/ssr-with-loading">
              ssr-with-loading
            </Link>
            <Link prefetch={false} href="/supabase/client-side">
              client-side
            </Link>
            <Link prefetch={false} href="/supabase/client-side-with-use">
              client-side-with-use
            </Link>
          </div>
          <hr />
          <div className={styles.row}>
            <p className={styles.heading}>fetch</p>
            <Link prefetch={false} href="/fetch/static">
              static
            </Link>
            <Link prefetch={false} href="/fetch/static-with-revalidate">
              static-with-revalidate
            </Link>
            <Link prefetch={false} href="/fetch/ssr">
              ssr
            </Link>
            <Link prefetch={false} href="/fetch/ssr-with-loading">
              ssr-with-loading
            </Link>
            <Link prefetch={false} href="/fetch/client-side">
              client-side
            </Link>
            <Link prefetch={false} href="/fetch/client-side-with-use">
              client-side-with-use
            </Link>
          </div>
        </nav>
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
